08:18:22 PM:DEBUG [logger_base.py:14] Mensaje a nivel debug
08:18:22 PM:INFO [logger_base.py:15] Mensaje a nivel info
08:18:22 PM:WARNING [logger_base.py:16] Mensaje a nivel warning
08:18:22 PM:ERROR [logger_base.py:17] Mensaje a nivel error
08:18:22 PM:CRITICAL [logger_base.py:18] Mensaje a nivel critical
07:28:49 PM:DEBUG [Persona.py:53] 
            Id Persona 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com

07:36:45 PM:DEBUG [Persona.py:53] 
            Id Persona 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com

07:37:33 PM:DEBUG [Persona.py:53] 
            Id Persona 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com

07:37:51 PM:DEBUG [Persona.py:53] 
            Id Persona 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com

07:37:51 PM:DEBUG [Persona.py:55] 
            Id Persona None,
            Nombre: Jose,
            Apellido: Lepez,
            Email: ljose@mail.com

08:19:49 PM:DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x0000020816F93120; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:22:04 PM:DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x00000125354C3120; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:22:04 PM:ERROR [conexion.py:39] Ocurri un error 'NoneType' object has no attribute 'cursor'
08:24:13 PM:DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000001B4D5F13120; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:24:13 PM:DEBUG [conexion.py:36] Se abrio correctamente el cursor <cursor object at 0x000001B4D689B920; closed: 0>
07:59:59 PM:DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x0000021D0A912570; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:59:59 PM:DEBUG [conexion.py:36] Se abrio correctamente el cursor <cursor object at 0x0000021D0CA85380; closed: 0>
08:00:43 PM:DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000001EC173C2570; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:00:43 PM:DEBUG [conexion.py:36] Se abrio correctamente el cursor <cursor object at 0x000001EC19511460; closed: 0>
08:00:43 PM:DEBUG [persona_dao.py:35] 
            Id Persona 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com

08:00:43 PM:DEBUG [persona_dao.py:35] 
            Id Persona 2,
            Nombre: Belen,
            Apellido: Gomez,
            Email: bgomez@mail.com

08:42:24 PM:DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000002E24F262570; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:42:24 PM:DEBUG [conexion.py:36] Se abrio correctamente el cursor <cursor object at 0x000002E251721460; closed: 0>
08:42:24 PM:DEBUG [persona_dao.py:38] Persona Insertada: 
            Id Persona None,
            Nombre: Pedro,
            Apellido: Romero,
            Email: promero@mail.com

08:42:24 PM:DEBUG [persona_dao.py:47] Personas insertadas: 1
